parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: abisoft
    database_user: root
    database_password: wxcvbn93
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 99b7cb50770907c42ebc4ddaf4fd49b07c70582a
    database_path: null
