parameters:
#    abisoft.example.class: Abisoft\AbisoftBundle\Example

services:
#    abisoft.example:
#        class: %abisoft.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
